UPDATE `REALESTATE` SET 
`BESIDE`='BESIDEPARKINGUNDERGROUND,BESIDEPARKINGLOT,BESIDEPARKINGMULTILEVEL,BESIDEPARKINGCOVERED,BESIDEPARKINGPROTECTION,BESIDEGOODTRANSPORTINTERCHANGE'
WHERE `IDREALESTATE`='18'