SELECT IDREALESTATE, PROPERTY FROM realestate.REALESTATE
WHERE FIND_IN_SET('ELECTRONMONEY', `CHECKBOXES`) > 0
AND FIND_IN_SET('ISDOCUMENT', `CHECKBOXES`) > 0
AND FIND_IN_SET('CARD', `CHECKBOXES`) > 0
AND FIND_IN_SET('ENGINEERINGGAS', `CHECKBOXES`) > 0
AND FIND_IN_SET('ENGINEERINGELECTRICITY', `CHECKBOXES`) > 0
AND FIND_IN_SET('ENGINEERINGHOTWATER', `CHECKBOXES`) > 0
AND FIND_IN_SET('ENGINEERINGSEWERAGE', `CHECKBOXES`) > 0
AND FIND_IN_SET('ENGINEERINGINTERNET', `CHECKBOXES`) > 0
AND FIND_IN_SET('BESIDEPARKINGUNDERGROUND', `CHECKBOXES`) > 0
AND FIND_IN_SET('BESIDEPARKINGMULTILEVEL', `CHECKBOXES`) > 0
AND FIND_IN_SET('BESIDEPARKINGPROTECTION', `CHECKBOXES`) > 0
AND FIND_IN_SET('BESIDEPARKINGCOVERED', `CHECKBOXES`) > 0
AND DEAL = 'SELL'