SELECT IDREALESTATE, PROPERTY FROM REALESTATE2
INNER JOIN 
((SELECT IDREALESTATE as `IDCHECKBOXES`, CHECKBOXES FROM realestate.REALESTATE2CHECKBOXES
WHERE FIND_IN_SET('ISDOCUMENT', `CHECKBOXES`) > 0
AND FIND_IN_SET('PREPAYMENT', `CHECKBOXES`) > 0
AND FIND_IN_SET('CASH', `CHECKBOXES`) > 0
AND FIND_IN_SET('ENGINEERINGGAS', `CHECKBOXES`) > 0
AND FIND_IN_SET('ENGINEERINGELECTRICITY', `CHECKBOXES`) > 0
AND FIND_IN_SET('ENGINEERINGHOTWATER', `CHECKBOXES`) > 0
AND FIND_IN_SET('ENGINEERINGSEWERAGE', `CHECKBOXES`) > 0
AND FIND_IN_SET('ENGINEERINGINTERNET', `CHECKBOXES`) > 0
AND FIND_IN_SET('BESIDEPARKINGUNDERGROUND', `CHECKBOXES`) > 0
AND FIND_IN_SET('BESIDEPARKINGMULTILEVEL', `CHECKBOXES`) > 0
AND FIND_IN_SET('BESIDEPARKINGPROTECTION', `CHECKBOXES`) > 0
AND FIND_IN_SET('BESIDEPARKINGCOVERED', `CHECKBOXES`) > 0) as `CHECKBOXES`)
ON IDCHECKBOXES = `realestate`.REALESTATE2.IDREALESTATE
WHERE DEAL = 'SELL'