SELECT * FROM TEST1
WHERE FIND_IN_SET('1', `SET`) > 0
AND FIND_IN_SET('3', `SET`) > 0
AND FIND_IN_SET('5', `SET`) > 0
AND FIND_IN_SET('7', `SET`) > 0
AND FIND_IN_SET('9', `SET`) > 0
AND FIND_IN_SET('11', `SET`) > 0
AND FIND_IN_SET('13', `SET`) > 0
AND FIND_IN_SET('15', `SET`) > 0
AND FIND_IN_SET('17', `SET`) > 0
AND FIND_IN_SET('19', `SET`) > 0
AND FIND_IN_SET('21', `SET`) > 0
AND FIND_IN_SET('23', `SET`) > 0
AND FIND_IN_SET('25', `SET`) > 0
AND FIND_IN_SET('27', `SET`) > 0
AND FIND_IN_SET('29', `SET`) > 0
