CREATE TABLE `НЕДВИЖИМОСТЬ` (
  `ИДЕНТИФИКАТОР` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID этой недвижимости',
  `ИД_ПОЛЬЗОВАТЕЛЯ` int(10) unsigned DEFAULT NULL COMMENT 'ID пользователя кому пренадлежит эта недвижимость',
  `ИД_МЕСТА` int(10) unsigned DEFAULT NULL COMMENT 'ID места-адреса этой недвижимости',
  `ТЕКСТ` char(255) DEFAULT NULL COMMENT 'Описание этой недвижимости',
  `СДЕЛКА` enum('ПРОДАЖА','ПОКУПКА','ОБМЕН','ПРОДАЖА_АРЕНДЫ','ПОКУПКА_АРЕНДЫ') DEFAULT NULL COMMENT 'Тип сделки для этой недвижимости',
  `ДАТА_СОЗДАНИЯ` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'дата создания этого обьявления недвижимости',
  `ДАТА_ОБНОВЛЕНИЯ` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'дата обновления этого объявления недвижимости',
  `ЦЕНА` bigint(20) unsigned DEFAULT NULL COMMENT 'Цена этой недвижимости',
  `ВАЛЮТА` enum('₽','$','€','¥') DEFAULT '₽' COMMENT 'Валюта цены для этой недвижимости',
  `НОМЕР_КАДАСТРОВЫЙ` char(20) DEFAULT NULL COMMENT 'кадастровый номер этой недвижимости',
  `НОМЕР_ОБЪЯВЛЕНИЯ` int(10) unsigned DEFAULT NULL COMMENT 'порядковый номер этого объявления для того чтобы знать в какой папке лежат фотки',
  `ОТМЕЧЕННЫЕ_ПУНКТЫ` set('ПО_ДОГОВОРЕННОСТИ','ЕСТЬ_ДОКУМЕНТЫ','ЭЛЕКТРОННЫЕ_ДЕНЬГИ','ПРЕДОПЛАТА','БАНКОВСКАЯ_КАРТА','НАЛИЧКА','DEALTESTDRIVE','ЭЛЕКТРИЧЕСТВО','ОТОПЛЕНИЕ','ГОРЯЧАЯ_ВОДА','ХОЛОДНАЯ_ВОДА','ГАЗ','ВЕНТИЛЯЦИЯ','КАНАЛИЗАЦИЯ','ЛИФТ','ДОМОФОН','ИНТЕРНЕТ','ПОДЗЕМНЫЙ_ПАРКИНГ','ОТКРЫТАЯ_СТОЯНКА','МНОГОУРОВНЕВЫЙ_ПАРКИНГ','КРЫТАЯ_СТОЯНКА','ОХРАНЯЕМАЯ','ХОРОШАЯ_ТРАНСПОРТНАЯ_РАЗВЯЗКА') DEFAULT NULL COMMENT 'Различные чекбоксы для объявления недвижимости',
  `ПЛОЩАДЬ` float unsigned DEFAULT NULL COMMENT 'Общая площадь',
  `КОМНАТ_ВСЕГО` tinyint(3) unsigned DEFAULT NULL COMMENT 'Общее количество комнат',
  `КОМНАТ_ДЛЯ_СДЕЛКИ` tinyint(3) unsigned DEFAULT NULL COMMENT 'Количество комнат для любого вида сделки',
  `ДОЛЯ` float unsigned DEFAULT NULL COMMENT 'Комнат в собственности',
  `МАТЕРИАЛ` enum('ПАНЕЛЬНОЕ','МОНОЛИТНОЕ','БЛОЧНОЕ','КИРПИЧНОЕ','ДЕРЕВЯННОЕ','ЖЕЛЕЗОБЕТОННОЕ','МЕТАЛЛИЧЕСКОЕ') DEFAULT NULL COMMENT 'Основной материал недвижимости',
  `ЭТАЖЕЙ_ВСЕГО` tinyint(3) unsigned DEFAULT NULL COMMENT 'Общее количество этажей',
  `ЭТАЖ` tinyint(3) unsigned DEFAULT NULL COMMENT 'Этаж на котором находится недвижимость',
  `ФУНДАМЕНТ` enum('ЛЕНТОЧНЫЙ','СТОЛБЧАТЫЙ','ПЛИТНЫЙ','КОНТИНУАЛЬНЫЙ') DEFAULT NULL COMMENT 'Фундамент',
  `АДРЕС` char(60) DEFAULT NULL COMMENT 'Короткий адрес недвижимости',
  `ВЫСОТА_ПОТОЛКА` float unsigned DEFAULT NULL COMMENT 'Высота этажа \\ потолка',
  `ДОЛЕВАЯ_СОБСТВЕННОСТЬ` enum('ЛИЧНАЯ','ДОЛЕВАЯ') DEFAULT 'ЛИЧНАЯ',
  `ОТОПЛЕНИЕ` enum('ПЕЧНОЕ','ГАЗОВОЕ','ВОДЯНОЕ','ЭЛЕКТРИЧЕСКОЕ','ВОЗДУШНОЕ') DEFAULT NULL,
  PRIMARY KEY (`ИДЕНТИФИКАТОР`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
