SELECT 
    DEAL,
    PROPERTY,
    SPACETOTAL,
    NAME AS `ADDRESS`,
    PRICE,
    CURRENCY,
    REALESTATE.CHECKBOXES AS `CHECKBOXES`,
    NUMBER,
    lat,
    lng,
    USER.ID AS `IDUSER`,
    REALESTATE.IDREALESTATE AS `IDREALESTATE`,
    TEXT,
    APARTMENTINTEGRITY,
    APARTMENTQUANTITYROOMS,
    APARTMENTTYPEHOUSE,
    APARTMENTNUMBEROFSTOREYS,
    APARTMENTFLOOR
FROM
    REALESTATE
        INNER JOIN
    REALESTATEAPARTMENT ON REALESTATE.IDREALESTATE = REALESTATEAPARTMENT.IDREALESTATE
        INNER JOIN
    PLACE ON REALESTATE.IDPLACE = PLACE.IDPLACE
        INNER JOIN
    USER ON REALESTATE.IDUSER = USER.ID
WHERE
    REALESTATE.IDPLACE IN (SELECT DISTINCT
            IDPLACE
        FROM
            ADDRESS_COMPONENTS
        WHERE
            IDPLACE IN (SELECT 
                    IDPLACE
                FROM
                    ADDRESS_COMPONENTS
                WHERE
                    long_name = 'Россия'))
        AND REALESTATE.PROPERTY = 'APARTMENT'
LIMIT 10